Repository sagebind/isahc, pull requests merged in 2019-11, with the labels that each got.

#88 Metrics API
  .github/workflows/ci.yml
  Cargo.toml
  examples/progress.rs
  src/agent.rs
  src/client.rs
  src/config.rs
  src/handler.rs
  src/lib.rs
  src/metrics.rs
  src/request.rs
  src/response.rs
  tests/metrics.rs
  tests/redirects.rs
Labels: feature

#115 HTTP auth API
  .github/workflows/ci.yml
  Cargo.toml
  README.md
  src/auth.rs
  src/client.rs
  src/config.rs
  src/lib.rs
  src/request.rs
  tests/auth.rs
Labels: feature

#121 Document json feature in examples
  examples/json.rs
Labels: documentation

#116 Upgrade to futures 0.3
  .github/workflows/ci.yml
  Cargo.toml
  examples/async.rs
  src/body.rs
  src/client.rs
  src/handler.rs
  src/lib.rs
Labels: dependencies

#128 Separate various SSL options into individual flags
  examples/badssl.rs
  src/auth.rs
  src/client.rs
  src/config/mod.rs
  src/config/ssl.rs
  src/request.rs
Labels: enhancement

#129 Add new VersionNegotiation API
  examples/http2.rs
  src/client.rs
  src/config/mod.rs
  src/request.rs
  tests/version.rs
Labels: enhancement

#131 Only request upgrade to HTTP/2 if it is available
  src/config/mod.rs
Labels: bug
